quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Investimentos
quarkus.smallrye-openapi.info-version=1.0.0

quarkus.jackson.serialization.write-dates-as-timestamps=false
quarkus.jackson.time-zone=UTC