mp.jwt.verify.publickey.location=META-INF/publicKey.pem
mp.jwt.verify.issuer=caixaverso-api
quarkus.http.auth.permission.public.paths=/v1/token
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.protected.paths=/v1/*
quarkus.http.auth.permission.protected.policy=authenticated

quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=investimentos_dev;encrypt=true;trustServerCertificate=true
quarkus.datasource.username=sa
quarkus.datasource.password=teste123
quarkus.datasource.jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.show-sql=true
quarkus.datasource.jdbc.trace=true
quarkus.hibernate-orm.database.generation=drop-and-create
app.carregar-dados=true